apiVersion: apps/v1
kind: Deployment
metadata:
  name: meyasubako-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meyasubako-ui
  template:
    metadata:
      labels:
        app: meyasubako-ui
    spec:
      containers:
        - name: react
          image: nkoguchi00dev/meyasubako-ui # Edit
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meyasubako-ui
spec:
  type: LoadBalancer
  selector:
    app: meyasubako-ui
  ports:
    - port: 3001
      targetPort: 80
      protocol: TCP
      name: meyasubako-ui
